export const orderConstants = {
  ORDER_CREATE_REQUEST: `ORDER_CREATE_REQUEST`,
  ORDER_CREATE_SUCCESS: `ORDER_CREATE_SUCCESS`,
  ORDER_CREATE_FAIL: `ORDER_CREATE_FAIL`,

  ORDER_FETCH_REQUEST: `ORDER_FETCH_REQUEST`,
  ORDER_FETCH_SUCCESS: `ORDER_FETCH_SUCCESS`,
  ORDER_FETCH_FAIL: `ORDER_FETCH_FAIL`,

  ORDER_DETAILS_FETCH_REQUEST: `ORDER_DETAILS_FETCH_REQUEST`,
  ORDER_DETAILS_FETCH_SUCCESS: `ORDER_DETAILS_FETCH_SUCCESS`,
  ORDER_DETAILS_FETCH_FAIL: `ORDER_DETAILS_FETCH_FAIL`,

  ORDER_ITEMS_FETCH_REQUEST: `ORDER_ITEMS_FETCH_REQUEST`,
  ORDER_ITEMS_FETCH_SUCCESS: `ORDER_ITEMS_FETCH_SUCCESS`,
  ORDER_ITEMS_FETCH_FAIL: `ORDER_ITEMS_FETCH_FAIL`,

  ORDER_PAY_REQUEST: `ORDER_PAY_REQUEST`,
  ORDER_PAY_SUCCESS: `ORDER_PAY_SUCCESS`,
  ORDER_PAY_FAIL: `ORDER_PAY_FAIL`,
  ORDER_PAY_RESET: `ORDER_PAY_RESET`,

  ORDER_FETCH_DISTINCT_REQUEST: `ORDER_FETCH_DISTINCT_REQUEST`,
  ORDER_FETCH_DISTINCT_SUCCESS: `ORDER_FETCH_DISTINCT_SUCCESS`,
  ORDER_FETCH_DISTINCT_FAIL: `ORDER_FETCH_DISTINCT_FAIL`,

  ORDER_FETCH_ONE_REQUEST: `ORDER_FETCH_ONE_REQUEST`,
  ORDER_FETCH_ONE_SUCCESS: `ORDER_FETCH_ONE_SUCCESS`,
  ORDER_FETCH_ONE_FAIL: `ORDER_FETCH_ONE_FAIL`,
  ORDER_FETCH_ONE_RESET: `ORDER_FETCH_ONE_RESET`,

  ORDER_DELIVER_REQUEST: `ORDER_DELIVER_REQUEST`,
  ORDER_DELIVER_SUCCESS: `ORDER_DELIVER_SUCCESS`,
  ORDER_DELIVER_FAIL: `ORDER_DELIVER_FAIL`,
  ORDER_DELIVER_RESET: `ORDER_DELIVER_RESET`,
};
