export const reviewConstants = {
  PRODUCT_FETCH_REVIEWS_REQUEST: `PRODUCT_FETCH_REVIEWS_REQUEST`,
  PRODUCT_FETCH_REVIEWS_SUCCESS: `PRODUCT_FETCH_REVIEWS_SUCCESS`,
  PRODUCT_FETCH_REVIEWS_FAIL: `PRODUCT_FETCH_REVIEWS_FAIL`,
  PRODUCT_FETCH_REVIEWS_RESET: `PRODUCT_FETCH_REVIEWS_RESET`,

  PRODUCT_CREATE_REVIEWS_REQUEST: `PRODUCT_CREATE_REVIEWS_REQUEST`,
  PRODUCT_CREATE_REVIEWS_SUCCESS: `PRODUCT_CREATE_REVIEWS_SUCCESS`,
  PRODUCT_CREATE_REVIEWS_FAIL: `PRODUCT_CREATE_REVIEWS_FAIL`,
  PRODUCT_CREATE_REVIEWS_RESET: `PRODUCT_CREATE_REVIEWS_RESET`,
};
